//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ShineYatraApi.HotelSearch {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelAvailSearchHttpBinding", Namespace="http://search.hotel.com")]
    public partial class HotelAvailSearch : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getHotelImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHotelAvailSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        ///// <remarks/>
        //public HotelAvailSearch() {
        //    this.Url = global::ShineYatraApi.Properties.Settings.Default.ShineYatraApi_HotelAvailSearch_HotelAvailSearch;
        //    if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
        //        this.UseDefaultCredentials = true;
        //        this.useDefaultCredentialsSetExplicitly = false;
        //    }
        //    else {
        //        this.useDefaultCredentialsSetExplicitly = true;
        //    }
        //}
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getHotelImageCompletedEventHandler getHotelImageCompleted;
        
        /// <remarks/>
        public event getHotelAvailSearchCompletedEventHandler getHotelAvailSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://search.hotel.com", ResponseNamespace="http://search.hotel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public string getHotelImage(string in0) {
            object[] results = this.Invoke("getHotelImage", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getHotelImageAsync(string in0) {
            this.getHotelImageAsync(in0, null);
        }
        
        /// <remarks/>
        public void getHotelImageAsync(string in0, object userState) {
            if ((this.getHotelImageOperationCompleted == null)) {
                this.getHotelImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotelImageOperationCompleted);
            }
            this.InvokeAsync("getHotelImage", new object[] {
                        in0}, this.getHotelImageOperationCompleted, userState);
        }
        
        private void OngetHotelImageOperationCompleted(object arg) {
            if ((this.getHotelImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotelImageCompleted(this, new getHotelImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://search.hotel.com", ResponseNamespace="http://search.hotel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public string getHotelAvailSearch(string in0, string in1) {
            object[] results = this.Invoke("getHotelAvailSearch", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getHotelAvailSearchAsync(string in0, string in1) {
            this.getHotelAvailSearchAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getHotelAvailSearchAsync(string in0, string in1, object userState) {
            if ((this.getHotelAvailSearchOperationCompleted == null)) {
                this.getHotelAvailSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotelAvailSearchOperationCompleted);
            }
            this.InvokeAsync("getHotelAvailSearch", new object[] {
                        in0,
                        in1}, this.getHotelAvailSearchOperationCompleted, userState);
        }
        
        private void OngetHotelAvailSearchOperationCompleted(object arg) {
            if ((this.getHotelAvailSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotelAvailSearchCompleted(this, new getHotelAvailSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getHotelImageCompletedEventHandler(object sender, getHotelImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotelImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotelImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getHotelAvailSearchCompletedEventHandler(object sender, getHotelAvailSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotelAvailSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotelAvailSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591