//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShineYatraApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/ArzooWS/services/DOMFlightAvailability")]
        public string ShineYatraApi_Search_DOMFlightAvailability {
            get {
                return ((string)(this["ShineYatraApi_Search_DOMFlightAvailability"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/ArzooWS/services/DOMFlightPricing")]
        public string ShineYatraApi_FlightPricing_DOMFlightPricing {
            get {
                return ((string)(this["ShineYatraApi_FlightPricing_DOMFlightPricing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/ArzooWS/services/DOMFlightBooking")]
        public string ShineYatraApi_FlightBooking_DOMFlightBooking {
            get {
                return ((string)(this["ShineYatraApi_FlightBooking_DOMFlightBooking"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/ArzooWS/services/DOMFlightBookingStatus")]
        public string ShineYatraApi_FlightBookingStatus_DOMFlightBookingStatus {
            get {
                return ((string)(this["ShineYatraApi_FlightBookingStatus_DOMFlightBookingStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/ArzooWS/services/DOMFlightCancellation")]
        public string ShineYatraApi_FlightCancellationRequest_DOMFlightCancellation {
            get {
                return ((string)(this["ShineYatraApi_FlightCancellationRequest_DOMFlightCancellation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/ArzooWS/services/DOMFlightCancellationStatus")]
        public string ShineYatraApi_CanellationRequestStatus_DOMFlightCancellationStatus {
            get {
                return ((string)(this["ShineYatraApi_CanellationRequestStatus_DOMFlightCancellationStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/HotelXML_V1.2/services/HotelAvailSearch")]
        public string ShineYatraApi_HotelSearch_HotelAvailSearch {
            get {
                return ((string)(this["ShineYatraApi_HotelSearch_HotelAvailSearch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/HotelXML_V1.2/services/HotelDetails")]
        public string ShineYatraApi_HotelDescription_HotelDetails {
            get {
                return ((string)(this["ShineYatraApi_HotelDescription_HotelDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/HotelXML_V1.2/services/HotelPolicy")]
        public string ShineYatraApi_HotelPolicyApi_HotelPolicy {
            get {
                return ((string)(this["ShineYatraApi_HotelPolicyApi_HotelPolicy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/HotelXML_V1.2/services/HotelBooking")]
        public string ShineYatraApi_HotelBookingConfirmation_HotelBooking {
            get {
                return ((string)(this["ShineYatraApi_HotelBookingConfirmation_HotelBooking"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/HotelXML_V1.2/services/HotelCancellation")]
        public string ShineYatraApi_HotelCancellationService_HotelCancellation {
            get {
                return ((string)(this["ShineYatraApi_HotelCancellationService_HotelCancellation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.arzoo.com/HotelXML_V1.2/services/HotelProvisional")]
        public string ShineYatraApi_HotelProvisionalBooking_HotelProvisional {
            get {
                return ((string)(this["ShineYatraApi_HotelProvisionalBooking_HotelProvisional"]));
            }
        }
    }
}
